version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: build
          command: docker build -t vimage:local .
      - run:
          name: run_local
          command: docker run vimage:local

